### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by d-belleza** [d-belleza/covid-traveling#15]
## Create [modal](https://materializecss.com/modals.html) or [toast](https://materializecss.com/toasts.html) for error handling:

- User must submit To and From cities - Done
- Cities are not found - link w/ failed API request, if 400 error code is returned, modal pops up stating, "Please ensure that you are searching by valid airport codes"
- User must submit Outgoing and Ingoing dates - Done
- Ingoing date must not be before Outgoing date - Done

**Comment by melissabcadena** [comment]
- Need to add error handling for if user tries to Save Trip that has already been saved.

**Comment by melissabcadena** [comment]
Need to also add error handling if inbound and outbound date are the same. Also, after search is submitted need to show city code in all caps

**Comment by melissabcadena** [comment]
Added all error handling. Only issue is that Flight Options div still shows up even if fetch returns a bad request error message.
