### ISSUE TITLE
Load Info to Page 

### ISSUE THREAD

**Issue by melissabcadena** [d-belleza/covid-traveling#3]
# Create a function that will populate below information from API fetch to the page

## Covid Data

New Cases
Total Cases
New Deaths
Total Deaths
Restriction Level - has background color (green, yellow, red) based on level
Notes
Last Update

## Flight Routes

Airlines
Minimum Price

**Comment by judhowland** [comment]
I've added the COVID Data from the one API still based on a hard-coded pass of the locations and dates. It will need some tweaking for styling but it functions within the updated html.index file having removed the hard-coded information.

**Comment by judhowland** [comment]
The above code for the COVID data was merged with develop. It was created within the feature/load-info branch

**Comment by melissabcadena** [comment]
- COVID Data load to page is completed

- Need to work on adding Flight Options to Page

> - Each card containing airport information should be clickable which will lead to Google Flights page that corresponds with their trip

**Comment by d-belleza** [comment]
Completed clickable to Google Flights page. Pushed to develop
